Fe bus api pop up
phuef/Geoinformation-in-Society-22 pull request #105
Opened 2023-01-09 15:00 UTC by jbalzer12

I added a popup to the markers with information about the bus stations name and future departures:

<img width="350" alt="Bildschirm­foto 2023-01-09 um 16 00 38" src="https://user-images.githubusercontent.com/61976072/211338607-197a787f-7b49-4b32-81b1-ca0caf396e51.png">

2023-01-10 11:50 UTC, phuef approved these changes

2023-01-10 13:47 UTC, kardwen requested changes

2023-01-10 13:47 UTC, kardwen commented on frontend/src/components/MapView.vue
> +                popup +=
Please use template literals for complex string formatting
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2023-01-10 13:47 UTC, kardwen commented on frontend/src/components/MapView.vue
> +              var popup =
Please don't use var unless there is a good reason to use it because of var hoisting
https://medium.com/@codingsam/awesome-javascript-no-more-var-working-title-999428999994
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var

2023-01-10 13:47 UTC, kardwen commented on frontend/src/components/MapView.vue
> +    async doBusStationRequest(nr) {
Can you please rename it to something like `requestBusStationInfo` so that it is easier to understand by the function name what the result of the request is?

2023-01-10 13:47 UTC, kardwen commented on frontend/src/components/MapView.vue
> +        onEachFeature: function (_feature, layer) {
Which features can you pass into this function?

2023-01-10 13:50 UTC, kardwen commented on frontend/src/components/MapView.vue
> +    async doBusStationRequest(nr) {
Also this funtion isn't used

2023-01-10 14:14 UTC, jbalzer12 commented on frontend/src/components/MapView.vue
> +        onEachFeature: function (_feature, layer) {
The point features from this layer usually. Here the _feature won't be called, but if I remove it, the whole constructor doesn't work anymore

2023-01-10 14:48 UTC, jbalzer12 commented on frontend/src/components/MapView.vue
> +              var popup =
und was soll ich stattdessen nutzen?

2023-01-10 14:52 UTC, jbalzer12 commented on frontend/src/components/MapView.vue
> +              var popup =
habs zu let geändert. meinst du das? const geht ja nicht

2023-01-10 14:55 UTC, jbalzer12 commented on frontend/src/components/MapView.vue
> +                popup +=
Thank you for this hint! I will change it

2023-01-12 11:10 UTC, kardwen approved these changes

2023-01-12 11:10 UTC, kardwen commented on frontend/src/components/MapView.vue
> +        onEachFeature: function (_feature, layer) {
you're right, it's an build-in function of leaflet

2023-01-12 11:11 UTC, merged